# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				warped_pearl = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				end_islands_enderman = true
				scarab = true
				swamp_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.create_things_and_misc]
				blaze_ballon_fire_projectile = true
				spout_gun_slime_projectile = true
				spout_gun_lava_projectile = true
				stoup_gun_water_projectile = true
				neon_tube_projectile = true
				sprinkler_head = true
				spout_gun_chocolate_projectile = true
				sprinkler_radius = true
				balloon_blaze = true
				spout_gun_honey_projectile = true

			[light_sources.settings.entities.immersiveengineering]
				explosive = true
				sawblade = true
				fusilier = true
				skyline_hook = true
				chemthrower_shot = true
				bulwark = true
				commando = true
				railgun_shot = true
				revolver_shot_wolfpack = true
				fluorescent_tube = true
				cart_reinforcedcrate = true
				revolver_shot_flare = true
				cart_woodencrate = true
				revolver_shot_homing = true
				cart_woodenbarrel = true
				revolver_shot = true
				cart_metalbarrel = true

			[light_sources.settings.entities.biomesoplenty]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.ae2]
				tiny_tnt_primed = true

			[light_sources.settings.entities.mekanism]
				robit = true
				flame = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				bamboo_hopper = true
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.create_sa]
				drill_module = true
				vault_module = true
				flamethrower_pr = true
				brass_cube_r = true
				fan_module = true
				flamethrower_pr_2 = true
				magnet_module = true
				brass_drone = true

			[light_sources.settings.entities.immersive_paintings]
				glow_graffiti = true
				painting = true
				graffiti = true
				glow_painting = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				jumping_spider = true
				leaf_insect = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				grappling_hook = true
				ferret = true
				otter = true
				red_panda = true
				sea_bunny = true

			[light_sources.settings.entities.sophisticatedbackpacks]
				everlasting_backpack_item = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				beach_creeper = true
				cave_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				birch_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.mcwfurnitures]
				chair = true
				couch = true

			[light_sources.settings.entities.railways]
				conductor = true
				benchcart = true
				jukeboxcart = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.blueprint]
				falling_block = true
				chest_boat = true
				boat = true

			[light_sources.settings.entities.ghosts]
				ghost = true
				kodama = true
				haunted_chest_boat = true
				haunted_boat = true
				small_ghost = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				plunderer = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.farm_and_charm]
				plow = true
				chair = true
				rotten_tomato = true
				cart = true

			[light_sources.settings.entities.tfmg]
				green_spark = true
				copper_grenade = true
				thermite_grenade = true
				spark = true
				dry_ice_flake = true
				napalm_bomb_entity = true
				blue_spark = true
				pipe_bomb = true
				zinc_grenade = true
				lithium_spark = true
				napalm_potato = true

			[light_sources.settings.entities.corpse]
				corpse = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	background_sleep = true
